# File: azure-pipelines.yml

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools
# TEMPORARY, include fake custom device to use templates until migrating the templates into build tools makes sense
    - repository: imitation-cd
      type: github
      ref: main
      endpoint: papowerNI
      name: papowerNI/imitation-cd

pool:
  name: custom-device-temp # TEMPORARY, eventually use an official build pool of custom device agents
  demands:
    - agent.os -equals Windows_NT

# --------- Build Parameters here ---------
parameters:
# Custom Device Name
  - name:    customDeviceRepoName
    type:    string
    default: niveristand-slsc-eds-custom-device

# LabVIEW Versions to Build
  - name:    lvVersions
    type:    object
    default:
      - version: '2020'
        bitness: '32-bit'

      - version: '2021'
        bitness: '64-bit'
      # TEMPORARY, disable 2023 since it's so buggy
      #- version: '2023'
      #  bitness: '64-bit'

# Custom Device Build Steps
  - name:    buildSteps
    type:    object
    default:
      - projectLocation: 'Source\SLSC EDS.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'Configuration Release'

      - projectLocation: 'Source\SLSC EDS.lvproj'
        buildOperation: 'ExecuteBuildSpecAllTargets'
        target: ''
        buildSpec: 'Engine Release'

# Build Output Location
  - name:    buildOutputLocation
    type:    string
    default: 'Built'

# Nipkg Installation Location
  - name:    nipkgInstallLocation
    type:    string
    default: 'documents\National Instruments\NI VeriStand $(lvVersion)\SLSC Plugins\Modules'

# Post-build Archive Location
  - name:    archiveLocation
    type:    string
    default: '\\nirvana\temp\papower\Measurements\VeriStandAddons\slsc_eds_custom_device'

# -----------------------------------------

# TEMPORARY: template files reference @imitation-cd instead of the build tools repo
stages:
  - stage: build
    jobs:
      # Iterate through all LabVIEW Versions & Bitnesses
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDeviceRepoName }} for LabVIEW ${{ lvVersion.version }}
          steps:
            - template: azure-templates\pre-job-steps.yml@imitation-cd # Configure variables, check out repos, Clear cache
              parameters:
                customDeviceRepoName:  ${{ parameters.customDeviceRepoName }}
                lvVersion:             ${{ lvVersion.version }}
                bitness:               ${{ lvVersion.bitness }}
                archiveLocation:       ${{ parameters.archiveLocation }}

            # Iterate through all Custom Device Build Steps
            - ${{ each buildStep in parameters.buildSteps }}:
              - template: azure-templates\build-op-steps.yml@imitation-cd # config file and build specs
                parameters:
                  projectLocation: ${{ buildStep.projectLocation }}
                  buildOperation:  ${{ buildStep.buildOperation }}
                  target:          ${{ buildStep.target }}
                  buildSpec:       ${{ buildStep.buildSpec }}

            - template: azure-templates\post-job-steps.yml@imitation-cd # nipkg and archive
              parameters:
                nipkgInstallLocation: ${{ parameters.nipkgInstallLocation }}
                buildOutputLocation:  ${{ parameters.buildOutputLocation }}
                pack:                 true