# test/POC pipeline for GitHub Veristand Custom Devices migration out of Jenkins

# Triggering: if there is a change to one of the branches below, run the pipeline
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# Repositories: include build tools (custom device repo included by default)
resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools
# TEMPORARY, include fake custom device to use templates until migrating the templates into build tools makes sense 
    - repository: imitation-cd
      type: github
      ref: main
      endpoint: papowerNI
      name: papowerNI/imitation-cd

# Pipeline-level Variables
variables:
  agentPool: custom-device-temp
  buildToolsRepo: niveristand-custom-device-build-tools
  templateLocation: '..\imitation-cd\azure-templates\build-steps.yaml'
  projectLocation: 'Source\SLSC EDS.lvproj'
  customDeviceName: niveristand-slsc-eds-custom-device
  shouldPack: true

stages:
  - stage: build

  # Agent Pool:  choose an agent that meets the following requirements
    pool:
      name: ${{ variables.agentPool }}
      demands:
        - agent.os -equals Windows_NT

    # Currently, no parallelism is needed so far, and no stages are needed so far
    jobs:
      - job: build_for_lv2020
        displayName: Build for LabVIEW 2020
        steps:
          - template: ${{ variables.templateLocation }}
            parameters:
              buildToolsRepo: ${{ variables.buildToolsRepo }}
              projectLocation: ${{ variables.projectLocation }}
              customDevice: ${{ variables.customDeviceName }}
              lvVersion: '2020'
              bitness: '32'
              pack: ${{ variables.shouldPack }}
      - job: build_for_lv2021
        displayName: Build for LabVIEW 2021
        steps:
          - template: ${{ variables.templateLocation }}
            parameters:
              buildToolsRepo: ${{ variables.buildToolsRepo }}
              projectLocation: ${{ variables.projectLocation }}
              customDevice: ${{ variables.customDeviceName }}
              lvVersion: '2021'
              bitness: '64'
              pack: ${{ variables.shouldPack }}
      - job: build_for_lv2023
        displayName: Build for LabVIEW 2023
        steps:
          - template: ${{ variables.templateLocation }}
            parameters:
              buildToolsRepo: ${{ variables.buildToolsRepo }}
              projectLocation: ${{ variables.projectLocation }}
              customDevice: ${{ variables.customDeviceName }}
              lvVersion: '2023'
              bitness: '64'
              pack: ${{ variables.shouldPack }}