# File: azure-pipelines.yml

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools
# TEMPORARY, include fake custom device to use templates until migrating the templates into build tools makes sense
    - repository: imitation-cd
      type: github
      ref: main
      endpoint: papowerNI
      name: papowerNI/imitation-cd

pool:
  name: custom-device-temp
  demands:
    - agent.os -equals Windows_NT

# --------- Build Parameters here ---------
parameters:
    # Custom Device Name
  - name: customDevice
    type: string
    default: niveristand-slsc-eds-custom-device
    # LabVIEW Versions to Build
  - name: lvVersions
    type: object
    default:
      - '2020'
      - '2021'
      - '2023'
    # Custom Device Build Steps (project location, LabVIEW CLI Build operation)
  - name: buildSteps
    type: object
    default:
      - ['Source\SLSC EDS.lvproj', 'ExecuteAllBuildSpecs']
# -----------------------------------------

# TEMPORARY: template files reference imitation-cd instead of the build tools repo
stages:
  - stage: build
    jobs:
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDevice }} for LabVIEW ${{ lvVersion}}
          steps:
            - template: azure-templates\pre-job-steps.yml@imitation-cd # Configure variables, check out repos, Clear cache
              parameters:
                customDevice: ${{ parameters.customDevice }}
                lvVersion: ${{ lvVersion}}
            - ${{ each buildStep in parameters.buildSteps }}:
              - template: azure-templates\build-op-steps.yml@imitation-cd # config file and build specs
                parameters:
                  projectLocation: ${{ buildStep[0] }}
                  buildOperation: ${{ buildStep[1] }}
            - template: azure-templates\post-job-steps.yml@imitation-cd # nipkg and archive
              parameters:
                pack: false