# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# if there is a change to one of the branches below, run the pipeline
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# use any agent with Windows
pool:
  name: Drivers-NIBuildFarm-RFMIBUILD
  demands:
    - agent.os -equals Windows_NT

resources:
  repositories:
    - repository: cd-build-tools
      type: git
      ref: main
      name: papower-vs-cd-build-tools

jobs:
# copy config files to lvproj locations
  - job: Build_2020
    displayName: Build custom device for LV 2020 32-bit
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 15
    steps:
      - checkout: self
        displayName: check out custom device
      - checkout: cd-build-tools
        displayName: check out build tools
      - script: copy "papower-vs-cd-build-tools\lvproj.config" "niveristand-slsc-eds-custom-device\Source\SLSC EDS.lvproj.config"
        displayName: copy lvproj config file
      - script: copy "papower-vs-cd-build-tools\LabVIEW.ini" "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.ini"
        displayName: copy lvproj config file
      - script: cd niveristand-slsc-eds-custom-device\Source && dir && cd "C:\Program Files (x86)\National Instruments\LabVIEW 2020\" && dir && type LabVIEW.ini
        displayName: display results to confirm it's working
      - script: LabVIEWCLI -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.exe" -OperationName ExecuteBuildSpec -ProjectPath niveristand-slsc-eds-custom-device\Source\SLSC EDS.lvproj -TargetName "My Computer" -BuildSpecName "Configuration Release"
        displayName: running Build Spec Configuration Release
      - script: LabVIEWCLI -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.exe" -OperationName ExecuteBuildSpec -ProjectPath niveristand-slsc-eds-custom-device\Source\SLSC EDS.lvproj -TargetName "My Computer" -BuildSpecName "Engine Release"
        displayName: running Build Spec Engine Release Windows
      - script: LabVIEWCLI -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2020\LabVIEW.exe" -OperationName ExecuteBuildSpec -ProjectPath niveristand-slsc-eds-custom-device\Source\SLSC EDS.lvproj -TargetName "Linux x64" -BuildSpecName "Engine Release"
        displayName: running Build Spec Engine Release Linux x64
      - script: echo copy files to archive
        displayName: copying built files to //nirvana archive
