trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools
# TEMPORARY, include fake custom device to use templates until migrating the templates into build tools makes sense
    - repository: imitation-cd
      type: github
      ref: main
      endpoint: papowerNI
      name: papowerNI/imitation-cd

pool:
  name: custom-device-temp # TEMPORARY, eventually use an official build pool of custom device agents
  demands:
    - agent.os -equals Windows_NT

# --------- Build Parameters here ---------
parameters:
    # customDeviceRepoName - Name of the Custom Device Repository on GitHub
  - name:    customDeviceRepoName
    type:    string
    default:  niveristand-slsc-eds-custom-device

    # lvVersions - each LabVIEW version, bitness, and release nomenclature combination to build
  - name:    lvVersions
    type:    object
    default:
      - version: '2020'
        bitness: '32-bit'
        releaseVersion: '20.0'
        quarterlyVersion: ''
      - version: '2021'
        bitness: '64-bit'
        releaseVersion: '21.0'
      # - version: '2023' TEMPORARY, disable 2023 build since LabVIEW is still buggy
      #   bitness: '64-bit'
      #   releaseVersion: '23.0'

    # buildOutputLocation - location where LV build outputs are stored
  - name:    buildOutputLocation
    type:    string
    default: 'Built'

    # packages - configuration for each nipkg to build
  - name:    packages
    type:    object
    default: 
      - installLocation: 'documents\National Instruments\NI VeriStand $(lvVersion)\SLSC Plugins\Modules'
        controlFileName: 'control'
        payloadLocation: 'Built'

    # archiveLocation - location to store build artifacts for archival
  - name:    archiveLocation
    type:    string
    default: '\\nirvana\temp\papower\Measurements\VeriStandAddons\slsc_eds_custom_device'

    # buildSteps - list of each project, buildOperation, target, and buildSpec combination to build 
    # Note: target and buildSpec may be empty for some buildOperations
  - name:    buildSteps
    type:    object
    default:
      - projectLocation: 'Source\SLSC EDS.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'Configuration Release'

      - projectLocation: 'Source\SLSC EDS.lvproj'
        buildOperation: 'ExecuteBuildSpecAllTargets'
        target: ''
        buildSpec: 'Engine Release'

# --------- Call Build Templates ---------
# Note: If custom build steps are needed for a particular custom device, they can be inserted before or after existing templates below
# TEMPORARY, point template locations to imitation-cd instead of build-tools while in development
stages:
  - stage: build
    jobs:
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDeviceRepoName }} for LabVIEW ${{ lvVersion.version }}
          steps:
            - template: azure-templates\pre-job-steps.yml@imitation-cd # Configure variables, check out repos, Clear cache
              parameters:
                customDeviceRepoName:  ${{ parameters.customDeviceRepoName }}
                lvVersion:             ${{ lvVersion.version }}
                bitness:               ${{ lvVersion.bitness }} 
                archiveLocation:       ${{ parameters.archiveLocation }}
                # dependencies:          ${{ parameters.dependencies }} No dependencies for SLSC EDS

            - ${{ each buildStep in parameters.buildSteps }}:
              - template: azure-templates\build-op-steps.yml@imitation-cd # config file and build specs
                parameters:
                  projectLocation: ${{ buildStep.projectLocation }}
                  buildOperation:  ${{ buildStep.buildOperation }}
                  target:          ${{ buildStep.target }}
                  buildSpec:       ${{ buildStep.buildSpec }}

            - ${{ each package in parameters.packages }}:
              - template: azure-templates\post-job-steps.yml@imitation-cd # nipkg and archive
                parameters:
                  package:             ${{ package }}
                  buildOutputLocation: ${{ parameters.buildOutputLocation }}
                  pack:                true