# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# if there is a change to one of the branches below, run the pipeline
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# use any agent with Windows
pool:
  name: Drivers-NIBuildFarm-RFMIBUILD
  demands:
    - agent.os -equals Windows_NT

resources:
  repositories:
    - repository: cd-build-tools
      type: git
      ref: main
      name: papower-vs-cd-build-tools

jobs:
# copy config files to lvproj locations
  - job: Build
    displayName: Copy lvproj.config files for LV Version
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 15
    steps:
      - checkout: self
        displayName: check out custom device
      - checkout: cd-build-tools
        displayName: check out build tools
      - script: cp "papower-vs-cd-build-tools\lvproj.config" "niveristand-slsc-eds-custom-device\Source\SLSC EDS.lvproj.config"
        displayName: copy lvproj config file
      - script: cd niveristand-slsc-eds-custom-device\Source; dir
        displayName: display results to confirm it's working
      - script: echo run build spec configuration
        displayName: running Build Spec Configuration Release
      - script: echo run build spec engine
        displayName: running Build Spec Engine Release
      - script: echo copy files to archive
        displayName: copying built files to //nirvana archive
